<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-03-27 22:59
=======
# Generated by Django 2.0.2 on 2018-03-23 16:25
>>>>>>> e4fe2af44ce442e64d6c364d527789deb22c51cf

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
>>>>>>> e4fe2af44ce442e64d6c364d527789deb22c51cf
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('parent_course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('parent_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
<<<<<<< HEAD
            name='parent_deck',
=======
            name='deck',
>>>>>>> e4fe2af44ce442e64d6c364d527789deb22c51cf
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Deck'),
        ),
    ]
